---
permalink: online-help/concept-managing-reports.html 
sidebar: sidebar 
keywords:  
summary: Active IQ Unified Manager では、Unified Managerユーザインターフェイスから直接レポートを作成および管理して、クラスタ内のストレージオブジェクトの健全性、容量、パフォーマンス、保護関係に関する情報を表示できます。この情報を確認することで、潜在的な問題を発生前に特定できます。 
---
= レポートの管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Manager では、Unified Managerユーザインターフェイスから直接レポートを作成および管理して、クラスタ内のストレージオブジェクトの健全性、容量、パフォーマンス、保護関係に関する情報を表示できます。この情報を確認することで、潜在的な問題を発生前に特定できます。

レポートは、カンマ区切り値（.csv）、Microsoft Excel（.xlsx）、またはPDFファイルとしてダウンロードできます。また、受信者のグループにEメールを使用してレポートを送信するようにスケジュール設定することもできます。レポートはEメールの添付ファイルとして送信されます。

ユーザインターフェイスからレポートを生成する以外に、次の方法でもUnified Managerから健全性とパフォーマンスのデータを抽出できます。

* Open Database Connectivity （ ODBC ）および ODBC のツールを使用してデータベースに直接アクセスし、クラスタ情報を取得する
* Unified Manager REST API を使用して確認したい情報を取得する


このリリースのActive IQ Unified Manager では、レポートの機能が次のように拡張されています。

* 設定したスケジュールに従ってレポートの E メールが送信されます。オンデマンドレポートを生成した場合でも、 E メールが送信されます。
* レポートのファイル名とレポートのメタデータには、レポートの生成元のホスト名が含まれます。
+
ファイル名が変更された場合でも、この機能強化によりレポートの生成元のホスト名を特定できます。


