---
permalink: online-help/reference-health-all-nodes-view.html 
sidebar: sidebar 
keywords:  
summary: Health：All Nodesビューを使用すると、Unified Managerで管理しているすべてのクラスタ内のノードに関する詳細情報を表示できます。 
---
= Health：All Nodesビュー
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Health：All Nodesビューを使用すると、Unified Managerで管理しているすべてのクラスタ内のノードに関する詳細情報を表示できます。

ビューページ内のオブジェクトは、デフォルトでは、イベントの重大度に基づいてソートされます。重大イベントが報告されたオブジェクトが最初に表示され、そのあとに警告イベントが報告されたオブジェクトが表示されます。これにより、対処が必要な問題を簡単に特定できます。ノードグリッド内の各ノードには、ONTAP システムマネージャへのリンクがあります。このリンクをクリックすると、ONTAP System Managerで同じ保護関係が表示されます。

ページの上部にあるコントロールを使用すると、特定のビュー（健常性、パフォーマンス、容量など）の選択、特定のオブジェクトの検索、フィルタの作成と適用による表示データのリストの絞り込み、ページの列の追加と削除/並べ替え、ページ上のデータをにエクスポートします `.csv`、 `.pdf`または `.xlsx` ファイル。カスタマイズしたページをカスタムビューとして保存し、データのレポートを定期的に生成して E メールで送信するようにスケジュール設定できます。

レポート*メニューには、Unified Managerとその管理対象クラスタが外部ネットワークに接続されていないサイトにインストールされている場合に、*ハードウェアインベントリレポート*オプションが表示されます。このボタンをクリックすると、が生成され `.csv` ハードウェアのモデル番号とシリアル番号、ディスクのタイプと数、インストールされているライセンスなど、クラスタとノードのすべての情報を含むファイル。このレポート機能は、NetAppActive IQプラットフォームに接続されていないセキュアなサイトでの契約更新に役立ちます。

を参照してください xref:reference-node-health-fields.adoc[ノードの健全性フィールド] このページ上のすべてのフィールドの説明については、を参照してください。
