---
permalink: online-help/reference-network-interface-performance-information-page.html 
sidebar: sidebar 
keywords:  
summary: ネットワークインターフェイス/パフォーマンス情報ページを使用して、ネットワークインターフェイス（LIF）に設定されている属性のリストを表示してください。この情報は、パフォーマンス関連の疑問を解決するのに役立ちます。 
---
= Network Interface/Performance Informationページ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ネットワークインターフェイス/パフォーマンス情報ページを使用して、ネットワークインターフェイス（LIF）の設定済み属性のリストを表示します。この情報は、パフォーマンス関連の疑問を解決するのに役立ちます。



== ネットワークインターフェイスの属性

* * IP アドレス *
+
LIFに割り当てられているIPv4またはIPv6アドレス。1つのLIFに複数のIPアドレスを割り当てることができます。

* * 役割 *
+
ロールは、LIFを介してサポートされるトラフィックの種類を決定します。

+
LIFには次のいずれかのロールを指定できます。

+
** データ
** クラスタ
** ノード管理
** クラスタ間


* * フェイルオーバーグループ *
+
ネットワークインターフェイスに割り当てられているフェイルオーバーグループの名前。

+
このフィールドはネットワークLIFにのみ適用され、SAN（FC / iSCSI）LIFとNVMe LIFには適用されません。

* * フェイルオーバーポリシー *
+
LIFに割り当てられているフェイルオーバーポリシーの名前。

+
このフィールドはネットワークLIFにのみ適用され、SAN（FC / iSCSI）LIFとNVMe LIFには適用されません。

* * ホームポート *
+
このインターフェイスのホームポートとして定義されているノードとポートの名前。名前をクリックすると、ポート/パフォーマンスエクスプローラのページにポートの詳細が表示されます。

* * 現在のポート *
+
インターフェイスが現在ホストされているノードおよびポートの名前。名前をクリックすると、ポート/パフォーマンスエクスプローラのページにポートの詳細が表示されます。


