---
permalink: online-help/reference-aggregate-capacity-fields.html 
sidebar: sidebar 
keywords:  
summary: Aggregate Capacity and Utilizationレポートには次のフィールドがあり、カスタムビューやレポートで使用できます。 
---
= アグリゲート容量のフィールド
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Aggregate Capacity and Utilizationレポートには次のフィールドがあり、カスタムビューやレポートで使用できます。

* * 集計 *
+
アグリゲート名。

* *日次増加率
+
アグリゲートでの24時間ごとの増加率。

* *フルまでの日数*
+
アグリゲートの容量がフルに達するまでの推定日数。

* *オーバーコミット容量%*
+
アグリゲートオーバーコミットの割合。

* *使用可能なデータ%*
+
使用可能なデータ容量の割合。

* *使用可能なデータ容量*
+
使用可能なデータ容量。

* *使用済みデータ%*
+
使用済みデータ容量の割合。

* *使用済みデータ容量*
+
使用済みデータ容量。

* *合計データ容量*
+
合計データ容量（使用容量と使用可能容量を足したもの）。

* *使用済み論理スペース*
+
アグリゲートに格納されているデータの実際のサイズ。 ONTAP の Storage Efficiency テクノロジによる削減を適用する前のサイズです。

* * Snapshotリザーブの使用可能率
+
Snapshotコピーに使用できるスペースの量の割合。

* * Snapshotリザーブの使用可能容量*
+
Snapshotコピーに使用できるスペースの量。

* * Snapshotリザーブの使用率
+
SnapshotコピーがSnapshotリザーブで使用しているスペースの量の割合。

* * Snapshotリザーブの使用容量*
+
SnapshotコピーがSnapshotリザーブで使用しているスペースの量。

* * Snapshotリザーブの合計容量*
+
アグリゲートのSnapshotリザーブの合計容量。

* *クラウド階層の使用済みスペース*
+
クラウド階層で現在使用されているデータ容量。

* * クラウド階層 *
+
ONTAP での作成時に指定されたクラウド階層のオブジェクトストアの名前。

* * 状態 *
+
アグリゲートの現在の状態。

* * タイプ *
+
アグリゲートのタイプ：

+
** HDD
** ハイブリッド
+
HDDとSSDの組み合わせですが、Flash Poolは有効になっていません。

** ハイブリッド（Flash Pool）
+
HDDとSSDの組み合わせで、Flash Poolが有効になっています。

** SSD の場合
** SSD （ FabricPool ）
+
SSDとクラウド階層の組み合わせです

** HDD（FabricPool ）
+
HDDとクラウド階層の組み合わせです

** VMDisk（SDS）
+
仮想マシン内の仮想ディスク

** VMディスク（FabricPool ）
+
仮想ディスクとクラウド階層の組み合わせです

** LUN（FlexArray ）


* * RAID タイプ *
+
RAID構成タイプ。

* * SnapLock タイプ *
+
アグリゲートのSnapLock タイプ。「Compliance」、「Enterprise」、「Non-SnapLock」のいずれかです。

* * HAペア*
+
2つのノードを構成して得られるHAペア値。

* * ノード *
+
アグリゲートが含まれるノードの名前。

* * クラスタ *
+
クラスタ名。クラスタ名をクリックすると、そのクラスタの容量の詳細ページが表示されます。

* *クラスタFQDN *
+
クラスタの完全修飾ドメイン名（FQDN）。


