---
permalink: online-help/reference-performance-all-ports-view.html 
sidebar: sidebar 
keywords:  
summary: Performance：All Portsビューには、Unified Managerのインスタンスによって監視されている各ポートのパフォーマンスイベント、データ、および設定情報の概要が表示されます。このページでは、ポートのパフォーマンスを簡単に監視し、パフォーマンスの問題やしきい値イベントをトラブルシューティングすることができます。 
---
= Performance：All Portsビュー
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Performance：All Portsビューには、Unified Managerのインスタンスによって監視されている各ポートのパフォーマンスイベント、データ、および設定情報の概要が表示されます。このページでは、ポートのパフォーマンスを簡単に監視し、パフォーマンスの問題やしきい値イベントをトラブルシューティングすることができます。

[NOTE]
====
パフォーマンスカウンタの値は物理ポートについてのみ表示されます。VLANまたはインターフェイスグループのカウンタ値は表示されません。

====
ビューページ内のオブジェクトは、デフォルトでは、イベントの重大度に基づいてソートされます。重大イベントが報告されたオブジェクトが最初に表示され、そのあとに警告イベントが報告されたオブジェクトが表示されます。これにより、対処が必要な問題を簡単に特定できます。

ページの上部にあるコントロールを使用すると、特定のビュー（健常性、パフォーマンス、容量など）の選択、特定のオブジェクトの検索、フィルタの作成と適用による表示データのリストの絞り込み、ページの列の追加と削除/並べ替え、ページ上のデータをにエクスポートします `.csv`、 `.pdf`または `.xlsx` ファイル。カスタマイズしたページをカスタムビューとして保存し、データのレポートを定期的に生成して E メールで送信するようにスケジュール設定できます。

パフォーマンスしきい値ポリシーは、オブジェクトインベントリページの任意のオブジェクトに、*パフォーマンスしきい値ポリシーの割り当て*ボタンと*パフォーマンスしきい値ポリシーのクリア*ボタンを使用して割り当てまたはクリアできます。

を参照してください xref:reference-port-performance-fields.adoc[ポートパフォーマンスのフィールド] このページ上のすべてのフィールドの説明については、を参照してください。
