---
permalink: online-help/reference-performance-all-nodes-view.html 
sidebar: sidebar 
keywords:  
summary: Performance：All Nodesビューには、Unified Managerのインスタンスによって監視されている各ノードのパフォーマンスイベント、データ、および設定情報の概要が表示されます。このページでは、ノードのパフォーマンスを簡単に監視し、パフォーマンスの問題やしきい値イベントをトラブルシューティングすることができます。 
---
= Performance：All Nodesビュー
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Performance：All Nodesビューには、Unified Managerのインスタンスによって監視されている各ノードのパフォーマンスイベント、データ、および設定情報の概要が表示されます。このページでは、ノードのパフォーマンスを簡単に監視し、パフォーマンスの問題やしきい値イベントをトラブルシューティングすることができます。

ビューページ内のオブジェクトは、デフォルトでは、イベントの重大度に基づいてソートされます。重大イベントが報告されたオブジェクトが最初に表示され、そのあとに警告イベントが報告されたオブジェクトが表示されます。これにより、対処が必要な問題を簡単に特定できます。

ページの上部にあるコントロールを使用すると、特定のビュー（健常性、パフォーマンス、容量など）の選択、特定のオブジェクトの検索、フィルタの作成と適用による表示データのリストの絞り込み、ページの列の追加と削除/並べ替え、ページ上のデータをにエクスポートします `.csv`、 `.pdf`または `.xlsx` ファイル。カスタマイズしたページをカスタムビューとして保存し、データのレポートを定期的に生成して E メールで送信するようにスケジュール設定できます。

レポート*メニューには、Unified Managerとその管理対象クラスタが外部ネットワークに接続されていないサイトにインストールされている場合に、*ハードウェアインベントリレポート*オプションが表示されます。このボタンをクリックすると、が生成され `.csv` ハードウェアのモデル番号とシリアル番号、ディスクのタイプと数、インストールされているライセンスなど、クラスタとノードのすべての情報を含むファイル。このレポート機能は、NetAppActive IQプラットフォームに接続されていないセキュアなサイトでの契約更新に役立ちます。

パフォーマンスしきい値ポリシーは、オブジェクトインベントリページの任意のオブジェクトに、*パフォーマンスしきい値ポリシーの割り当て*ボタンと*パフォーマンスしきい値ポリシーのクリア*ボタンを使用して割り当てまたはクリアできます。

を参照してください xref:reference-node-performance-fields.adoc[ノードパフォーマンスのフィールド] このページ上のすべてのフィールドの説明については、を参照してください。
