---
permalink: online-help/reference-volume-capacity-fields.html 
sidebar: sidebar 
keywords:  
summary: Capacityでは次のフィールドを使用できます。All Volumes（すべてのボリューム）ビューで、カスタムビューやレポートで使用できます。 
---
= ボリューム容量のフィールド
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Capacityでは次のフィールドを使用できます。All Volumes（すべてのボリューム）ビューで、カスタムビューやレポートで使用できます。

* * 音量 *
+
ボリューム名。

* *日次増加率
+
ボリュームでの24時間ごとの増加率。

* *フルまでの日数*
+
ボリュームの容量がフルに達するまでの推定日数。

* *使用可能なデータ%*
+
ボリューム内の使用可能なデータ容量の割合。

* *使用可能なデータ容量*
+
ボリューム内の使用可能なデータ容量。

* *使用済みデータ%*
+
ボリューム内の使用済みデータの割合。

* *使用済みデータ容量*
+
ボリューム内の使用済みデータ容量。

* *合計データ容量*
+
ボリューム内の合計データ容量（使用容量と使用可能容量を足したもの）。

* *使用済み論理スペース*
+
このボリュームでデータに使用されている論理スペース。ONTAP のStorage Efficiencyテクノロジによる削減を適用する前のものです。

* * Snapshotオーバーフロー%*
+
Snapshotコピーで使用されているデータスペースの割合。

* * Snapshotリザーブの使用可能率
+
ボリュームでSnapshotコピーに使用可能なスペースの量の割合。

* * Snapshotリザーブの使用可能容量*
+
ボリュームでSnapshotコピーに使用可能なスペースの量。

* * Snapshotリザーブの使用率
+
ボリュームでSnapshotコピーに使用されているスペースの量の割合。

* * Snapshotリザーブの使用容量*
+
ボリュームでSnapshotコピーに使用されているスペースの量。

* * Snapshotリザーブの合計容量*
+
ボリューム内のSnapshotコピーの合計容量が表示されます。

* *クォータコミット容量*
+
ボリューム内のクォータ用にリザーブされているスペース。

* *クォータオーバーコミット容量*
+
「ボリュームクォータがオーバーコミット」イベントが生成される基準となるクォータ用のスペースの使用量。

* * inodeの総数*
+
ボリューム内のinodeの数。

* * inode使用率
+
ボリュームで使用されているinodeスペースの割合。

* * シンプロビジョニング *
+
選択したボリュームにスペースギャランティが設定されているかどうか。有効な値は「はい」と「いいえ」です

* * スペース保証 *
+
ボリュームに関連付けられているストレージギャランティオプション。

* * 自動拡張 *
+
スペースが不足したときにボリュームのサイズが自動的に拡張されるかどうか。

* * Snapshotの自動削除*
+
Snapshotコピーの自動削除が有効か無効か。

* * 重複排除 *
+
ボリュームで重複排除が有効か無効か。

* * 圧縮 *
+
ボリュームで圧縮が有効か無効か。

* * 状態 *
+
エクスポートされるボリュームの状態。

* *保護の役割*
+
ボリュームに設定されている保護の役割。

* * SnapLock タイプ *
+
ボリュームがSnapLock ボリュームかSnapLockなしのボリュームか。

* * SnapLock 有効期限*
+
SnapLock の有効期限。

* * 階層化ポリシー *
+
ボリュームに対して設定されている階層化ポリシー。FabricPool対応アグリゲートに導入した場合のみ有効です。

* *キャッシングポリシー*
+
選択したボリュームに関連付けられているキャッシングポリシー。

+
このポリシーは、Flash Poolのキャッシングがボリュームに対して実行される方法に関する情報を提供します。キャッシングポリシーの詳細については、「Health：All Volumes」ビューを参照してください。

* *キャッシュの保持優先度*
+
キャッシュされたプールの保持に使用される優先度。

* * Storage VM *
+
ボリュームが含まれているStorage Virtual Machine（SVM）の名前。

* * クラスタ *
+
ボリュームが配置されているクラスタの名前。クラスタ名をクリックすると、そのクラスタの健全性の詳細ページが表示されます。

* *クラスタFQDN *
+
クラスタの完全修飾ドメイン名（FQDN）。


