---
permalink: online-help/reference-volume-thresholds-page.html 
sidebar: sidebar 
keywords:  
summary: ボリュームしきい値ページでは、監視対象のボリュームのグローバル健全性しきい値を設定できます。個 々 のボリュームに対して、またはすべてのボリュームに対してグローバルにしきい値を設定できます。オプションをグローバルに設定すると、すべてのオブジェクトのデフォルト値が変更されます。ただし、オブジェクトレベルでデフォルト値が変更されている場合、グローバルな値は変更されません。 
---
= ボリュームしきい値ページ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ボリュームしきい値ページでは、監視対象のボリュームのグローバル健全性しきい値を設定できます。個 々 のボリュームに対して、またはすべてのボリュームに対してグローバルにしきい値を設定できます。オプションをグローバルに設定すると、すべてのオブジェクトのデフォルト値が変更されます。ただし、オブジェクトレベルでデフォルト値が変更されている場合、グローバルな値は変更されません。

アプリケーション管理者またはストレージ管理者のロールが必要です。

しきい値を超えるとイベントが生成されます。そのようなイベントに対して対処方法を実行できます。

容量、ボリュームのSnapshotコピー、qtreeクォータ、ボリュームの増加率、およびinodeについてしきい値を設定できます。



== 容量領域

容量領域では、ボリュームの容量について、次のしきい値条件を設定できます。ボリュームで自動拡張が有効になっている場合は、元のボリュームサイズではなく、自動拡張で設定された最大ボリュームサイズに基づいて、容量のしきい値を超えているかどうかが判定されることに注意してください。

* *スペースがほぼフル*
+
ボリュームがほぼフルであるとみなす割合を示します。

+
** デフォルト値：80%
+
管理サーバでイベントが生成されるように、このしきい値の値は「ボリュームがフル」のしきい値の値よりも小さくする必要があります。

** 生成されるイベント：ボリュームがほぼフルです
** イベントの重大度：警告


* *スペースがフル*
+
ボリュームがフルであるとみなす割合を示します。

+
** デフォルト値：90%
** 生成されるイベント：ボリュームがフルです
** イベントの重大度：エラー


* *フルまでの日数*
+
ボリュームの容量がフルに達するまでの残り日数を示します。

+
** デフォルト値：15（最小値でもあります）
** 生成されるイベント：ボリュームのフルまでの日数
** イベントの重大度：エラー






== Snapshotコピー領域

Snapshotコピー領域では、ボリューム内のSnapshotコピーについて、次のしきい値条件を設定できます。

* * Snapshotリザーブがフル*
+
Snapshotコピー用にリザーブされたスペースがフルであるとみなす割合を示します。

+
** デフォルト値：90%
** 生成されるイベント：ボリュームのSnapshotリザーブがフルです
** イベントの重大度：エラー


* *フルまでの日数*
+
Snapshotコピー用にリザーブされたスペースがフルに達するまでの残り日数を示します。

+
** デフォルト値：7
** 生成されるイベント：ボリュームのSnapshotリザーブのフルまでの日数
** イベントの重大度：エラー


* *カウント*
+
ボリュームのSnapshotコピーが多すぎるとみなす数を示します。

+
** デフォルト値：1000
** 生成されるイベント：Snapshotコピー数の上限を超えています
** イベントの重大度：エラーUnified Managerがイベントをトリガーする前のボリュームあたりの最大数とみなされるSnapshotコピーの数がONTAP の最大数を超えています。




[cols="3*"]
|===
|  | ONTAP 最大 | Unified Manager最大数 


 a| 
ONTAP 9.3以前を実行しているFlexVol ボリュームとONTAP 9.7以前を実行しているFlexGroup ボリューム
 a| 
255
 a| 
250



 a| 
ONTAP 9.4以降を実行しているFlexVol ボリュームおよびONTAP 9.8以降を実行しているFlexGroup ボリューム
 a| 
1、023
 a| 
1000

|===


== qtreeクォータ領域

qtreeクォータ領域では、ボリュームクォータについて、次のしきい値条件を設定できます。

* *ほぼオーバーコミット*
+
ボリュームのqtreeクォータがほぼオーバーコミットされているとみなす割合を示します。

+
** デフォルト値：95%
** 生成されるイベント：ボリュームのqtreeクォータがほぼオーバーコミットされています
** イベントの重大度：警告


* *オーバーコミット*
+
ボリュームのqtreeクォータがオーバーコミットされているとみなす割合を示します。

+
** デフォルト値は100%です
** 生成されるイベント：ボリュームのqtreeクォータがオーバーコミット
** イベントの重大度：エラー






== 成長領域

Growth領域では、ボリュームの増加率について、次のしきい値条件を設定できます。

* *増加率*
+
ボリュームの増加率が正常であるとみなす割合を示します。このしきい値を超えると、「ボリュームの増加率-異常」イベントが生成されます。

+
** デフォルト値：1%
** 生成されるイベント：ボリュームの増加率-異常
** イベントの重大度：警告


* *増加率係数*
+
ボリュームの増加率の標準偏差に適用される係数を示します。増加率が係数適用後の標準偏差を超えると、「ボリュームの増加率が異常」イベントが生成されます。

+
ボリュームが増加率の変化による影響を受けやすい場合は、増加率係数の値を小さくします。増加率係数の範囲は1~5です。

+
** デフォルト値：2


+
[NOTE]
====
グローバルしきい値レベルでボリュームの増加率係数を変更した場合、グローバルしきい値レベルのアグリゲートの増加率係数にも変更が適用されます。

====




== inode領域

inode領域では、inodeについて、次のしきい値条件を設定できます。

* *ほぼフル*
+
ボリュームのinodeがほぼ使用されているとみなす割合を示します。

+
** デフォルト値：80%
** 生成されるイベント：inodeがほぼフルです
** イベントの重大度：警告


* *フル*
+
ボリュームのinodeがすべて使用されているとみなす割合を示します。

+
** デフォルト値：90%
** 生成されるイベント：inodeがフルです
** イベントの重大度：エラー



