---
permalink: online-help/reference-lag-thresholds-for-unmanaged-relationships-page.html 
sidebar: sidebar 
keywords:  
summary: Relationship Thresholdsページでは、管理対象外の保護関係にグローバル遅延警告しきい値と遅延エラーしきい値を設定できます。これにより、遅延エラーまたはしきい値エラーが発生した場合に通知を受けて対処することができます。これらの設定に対する変更は、次にスケジュールされている更新で適用されます。 
---
= [Relationship Thresholds]ページ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Relationship Thresholdsページでは、管理対象外の保護関係にグローバル遅延警告しきい値と遅延エラーしきい値を設定できます。これにより、遅延エラーまたはしきい値エラーが発生した場合に通知を受けて対処することができます。これらの設定に対する変更は、次にスケジュールされている更新で適用されます。

アプリケーション管理者またはストレージ管理者のロールが必要です。

ボリュームまたはStorage VMのいずれかのしきい値を超えるとイベントが生成されます。そのようなイベントに対して対処方法を実行できます。Storage VM関係に対してイベントが生成されるようになりましたが、Storage VMディザスタリカバリ設定内のコンスティチュエント関係に対してはブロックされます。これにより、関係に対して発生しているイベントが多すぎることを防ぐことができます。管理対象外の関係に対する遅延しきい値の設定はデフォルトで有効になっており、Storage VMにも適用されます。

遅延しきい値では、遅延時間が超えてはならない割合を指定します。たとえば、1時間の例で遅延しきい値が150%と定義されている場合、遅延時間が1.5時間を超えるとイベントが生成されます。



== 管理対象外の関係の遅延しきい値領域

遅延領域では、次の条件について、管理対象外の関係の遅延しきい値を設定できます。

* * 警告 *
+
遅延時間が遅延警告しきい値に達した、あるいは超えたとみなす割合を指定します。

+
** デフォルト値は150%です
** 生成されるイベント：SnapMirror関係の遅延警告またはSnapVault 関係の遅延警告
** イベントの重大度：警告


* * エラー *
+
遅延時間が遅延エラーしきい値に達した、あるいは超えたとみなす割合を指定します。

+
** デフォルト値：250%
** 生成されるイベント：SnapMirror関係の遅延エラーまたはSnapVault 関係の遅延エラー
** イベントの重大度：エラー




また、警告またはエラーイベントが遅延しきい値の量からトリガーされないようにするには、有効の横のチェックボックスをオフにします。
