---
permalink: online-help/reference-aggregate-performance-information-page.html 
sidebar: sidebar 
keywords:  
summary: アグリゲート/パフォーマンス情報ページを使用して、アグリゲートの物理属性と論理属性のリストを表示します。この情報は、パフォーマンス関連の疑問を解決するのに役立ちます。 
---
= Aggregate / Performance Informationページに移動します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アグリゲート/パフォーマンス情報ページを使用して、アグリゲートの物理属性と論理属性のリストを表示します。この情報は、パフォーマンス関連の疑問を解決するのに役立ちます。



== アグリゲートの属性

* * タイプ *
+
アグリゲートのタイプ。

+
** HDD
** ハイブリッド
+
HDDとSSDの組み合わせですが、Flash Poolは有効になっていません。

** ハイブリッド（Flash Pool）
+
HDDとSSDの組み合わせで、Flash Poolが有効になっています。

** SSD の場合
** SSD （ FabricPool ）
+
SSDとクラウド階層の組み合わせです

** HDD（FabricPool ）
+
HDDとクラウド階層の組み合わせです

** VMDisk（SDS）
+
仮想マシン内の仮想ディスク

** VMディスク（FabricPool ）
+
仮想ディスクとクラウド階層の組み合わせです

** LUN（FlexArray ）


* * クラスタ *
+
アグリゲートが属するクラスタの名前。名前をクリックすると、クラスタ/パフォーマンスエクスプローラのページにクラスタの詳細を表示できます。

* * ノード *
+
アグリゲートのディスクが属するノードの名前。名前をクリックすると、ノード/パフォーマンスエクスプローラのページにノードの詳細を表示できます。

* * Flash Pool *
+
Flash Poolアグリゲートの場合は「はい」と「いいえ」のいずれかです

+
Flash Poolアグリゲートは、SSDとHDDの両方で構成されるハイブリッドアグリゲートです。

* * FabricPool *
+
FabricPool アグリゲートの場合は「はい」と「いいえ」のどちらですか

+
FabricPool アグリゲートは、SSDとクラウド階層、またはHDDとクラウド階層（ONTAP 9.8以降）で構成されるアグリゲートです。

* *非アクティブなデータレポート*
+
このアグリゲートでInactive Data Reporting機能が有効になっているかどうか。有効にすると、このアグリゲートのボリュームのパフォーマンス/ボリュームインベントリページにコールドデータの量が表示されます。

+
このフィールドの値は、ONTAP のバージョンが非アクティブデータレポートをサポートしていない場合は「N/A」です。

* *使用済み論理スペース*
+
このアグリゲートに格納されているデータの実際のサイズ。ONTAP のStorage Efficiencyテクノロジによる削減を適用する前のサイズです。


