---
permalink: online-help/reference-backup-settings-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: '[Backup Settings]ダイアログ・ボックスは、MySQLおよびNetApp Snapshotバックアップの設定に使用します。設定されているバックアップに応じて、[バックアップ設定]ダイアログボックスに関連フィールドが表示されます。MySQLデータベースのバックアップについては、選択したActive IQ Unified Manager インスタンスのバックアップスケジュール、保持数、およびバックアップパスを定義できます。' 
---
= Backup Settingsダイアログボックス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
[Backup Settings]ダイアログ・ボックスは、MySQLおよびNetApp Snapshotバックアップの設定に使用します。設定されているバックアップに応じて、[バックアップ設定]ダイアログボックスに関連フィールドが表示されます。MySQLデータベースのバックアップについては、選択したActive IQ Unified Manager インスタンスのバックアップスケジュール、保持数、およびバックアップパスを定義できます。

次のデータベースバックアップ設定を変更できます。

* *クラスタ*
+
Unified Managerのデータをホストするストレージシステムのクラスタ管理IPを指定する必要があります。

* *音量*
+
Unified Managerデータをホストする専用のLUNを含むボリュームの名前を指定する必要があります。

* * Storage VM *
+
Unified Managerのデータをホストする専用のLUNを含む、ボリュームが配置されているStorage VMの名前を指定する必要があります。

* * LUN *
+
バックアップのタイプがNetApp Snapshotである場合は、Unified ManagerデータをホストするLUNの名前を指定する必要があります。

* *マウントパス*
+
MySQLデータベースダンプバックアップ方式を使用している場合、このフィールドには、バックアップファイルの格納先のパスを指定します。Snapshotバックアップ方式を使用している場合は、バックアップを格納するクラスタ、Storage VM、およびボリュームが表示されます。

+
次の表に、バックアップパスの形式とデフォルトの場所をオペレーティングシステム別に示します。

+
[cols="2*"]
|===
| ホストオペレーティングシステム | バックアップパスの形式 


 a| 
仮想アプライアンス
 a| 
`/opt/netapp/data/ocum-backup`



 a| 
Red Hat Enterprise Linux または CentOS Linux
 a| 
`/data/ocum-backup`



 a| 
Microsoft Windows の場合
 a| 
Windowsの場合は、マウントパスを指定する必要があります。たとえば'マウント・パスがD`"ドライブの場合'マウント・パスをとして指定する必要があります `D:`

|===
* *保持数*
+
Unified Managerでバックアップを保持する最大数を指定します。デフォルト値は10です。

* *毎日スケジュール*
+
日次バックアップを実行する時刻を指定します。

* *毎週スケジュール*
+
週次バックアップを実行する曜日と時刻を指定します。

* * なし *
+
バックアップは作成されません。


