---
permalink: online-help/reference-cluster-capacity-fields.html 
sidebar: sidebar 
keywords:  
summary: Capacity：All Clustersビューでは次のフィールドを使用できます。これらのフィールドはカスタムビューとレポートで使用できます。 
---
= クラスタ容量のフィールド
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Capacity：All Clustersビューでは次のフィールドを使用できます。これらのフィールドはカスタムビューとレポートで使用できます。

* * クラスタ *
+
クラスタ名。クラスタ名をクリックすると、そのクラスタの容量の詳細ページが表示されます。

* *クラスタFQDN *
+
クラスタの完全修飾ドメイン名（FQDN）。

* * HAペア*
+
2つのノードを構成して得られるHAペア値。

* *合計物理容量*
+
アレイ内のすべてのディスクの合計物理容量が表示されます。

* *未設定の物理容量*
+
コンテナタイプが「アグリゲート」、「破損」、「スペア」、「共有」以外のディスクの未設定の容量。この容量は、ONTAP のディスクの物理容量よりも常に多くなります。たとえば、2TBのディスクがあるとします。ディスクの物理容量はONTAP では1.6TBですが、Unified Managerでの未設定の物理容量は1.8TBになります。

* *アグリゲート合計容量*
+
ユーザが使用可能なアグリゲートの合計サイズ。これにはSnapshotコピーリザーブが含まれます。

* *アグリゲートの使用容量*
+
アグリゲートですでに使用されている容量。これには、ボリューム、LUN、その他のStorage Efficiencyテクノロジのオーバーヘッドによって消費される容量も含まれます。

* *アグリゲート-未使用容量*
+
アグリゲートに追加データを格納するために使用できる容量。これにはSnapshotコピーリザーブが含まれます。

* *使用済み論理スペース*
+
このクラスタのすべてのアグリゲートに格納されているデータの実際のサイズ。 ONTAP の Storage Efficiency テクノロジによる削減を適用する前のサイズです。

* *データ削減*
+
ONTAP のStorage Efficiency設定に基づくデータ削減率。

* *割り当て済みLUN容量*
+
マッピングされているLUNの容量。

* *未割り当てのLUN容量*
+
ホストにマッピングされていないすべてのLUNの容量。

* *ボリューム合計容量*
+
ボリュームの合計容量（使用容量と未使用容量を足したもの）。

* *ボリュームの使用容量*
+
ボリュームの使用済み容量。

* *ボリューム-未使用容量*
+
ボリュームの未使用容量。

* *ボリュームの保護容量*
+
SnapMirrorとSnapVault が有効になっているボリュームの容量。

* *クラウド階層の使用済み容量（ライセンス済み）*
+
FabricPool ライセンスが必要なストレージプロバイダについて、クラウド階層でデータに使用されているスペース。

* *使用済みクラウド階層（その他）*
+
StorageGRID システムおよびONTAP S3プロトコルストアのクラウド階層で、FabricPool ライセンスが不要なデータに使用されているスペース。

* *モデル/ファミリー*
+
クラスタのモデルまたはファミリーの名前。

* * OSバージョン*
+
システムにインストールされているONTAP のバージョン。

* * 連絡先 *
+
クラスタの連絡先情報。

* * 場所 *
+
クラスタの場所。


