---
permalink: online-help/reference-what-ontap-issues-can-unified-manager-fix.html 
sidebar: sidebar 
keywords: fix it,fix all 
summary: この表では、 Unified Manager のユーザインターフェイスで Fix it ボタンまたは Fix All ボタンをクリックして直接解決できる ONTAP の問題について説明します。 
---
= Unified Managerで解決可能なONTAP の問題
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
次の表に、Unified Managerユーザインターフェイスで* Fix it *または* Fix All *ボタンをクリックして直接解決できるONTAP の問題を示します。

[cols="3*"]
|===
| イベント名と概要 | 管理操作 | 「Fix it」操作 


 a| 
ボリュームスペースがフルです

ボリュームにスペースがほとんど残っておらず、容量の「フル」しきい値を超えています。このしきい値は、デフォルトではボリュームサイズの 90% に設定されています。
 a| 
ボリュームの自動拡張を有効にする
 a| 
Unified Manager はこのボリュームにボリュームの自動拡張が設定されていないことを特定し、必要に応じてボリュームの容量が拡張されるようにこの機能を有効にします。



 a| 
inode がフルです

このボリュームの inode が不足しており、新しいファイルを受け入れることはできません。
 a| 
ボリュームの inode の数を増やします
 a| 
ボリュームの inode の数を 2% 増やします。



 a| 
ストレージ階層ポリシーの不一致が検出されました

ボリュームには大量の非アクティブデータがあり'現在の階層化ポリシーはスナップショットのみまたはなしに設定されています
 a| 
クラウドの自動階層化を有効化
 a| 
ボリュームはすでにFabricPool 上に存在しているため、非アクティブなデータが低コストのクラウド階層に移動されるように、階層化ポリシーを「auto」に変更します。



 a| 
ストレージ階層の不一致が検出されました

アクセス頻度の低いデータがボリュームに大量にありますが、クラウド対応のストレージ階層（ FabricPool ）に配置されていません。
 a| 
ボリュームのストレージ階層を変更します
 a| 
ボリュームをクラウド対応ストレージ階層に移動し、階層化ポリシーを「auto」に設定して、アクセス頻度の低いデータをクラウド階層に移動します。



 a| 
監査ログが無効です

Storage VM の監査ログが有効になっていません
 a| 
Storage VM の監査ログを有効にしてください
 a| 
Storage VM の監査ログを有効にします。

Storage VM にローカルまたはリモートの監査ログの場所が設定されている必要があります。



 a| 
ログインバナーが無効です

アクセス制限をクリアしてセキュリティを強化するには、クラスタのログインバナーを有効にする必要があります。
 a| 
クラスタのログインバナーを設定します
 a| 
クラスタ・ログイン・バナーを「許可されたユーザーにアクセス制限」に設定します。



 a| 
ログインバナーが無効です

アクセス制限を明確にしてセキュリティを強化するには、 Storage VM のログインバナーを有効にする必要があります。
 a| 
Storage VM のログインバナーを設定します
 a| 
Storage VMのログインバナーを「許可されたユーザにアクセス制限」に設定します。



 a| 
SSH でセキュアでない暗号が使用されています

サフィックスが「-cbc」の暗号は、安全でないと見なされます。
 a| 
セキュアでない暗号をクラスタから削除してください
 a| 
安全でない暗号（ aes192-cbc や aes128-cbc など）をクラスタから削除します。



 a| 
SSH でセキュアでない暗号が使用されています

サフィックスが「-cbc」の暗号は、安全でないと見なされます。
 a| 
セキュアでない暗号を Storage VM から削除してください
 a| 
安全でない暗号（ aes192-cbc や aes128-cbc など）をストレージ VM から削除します。



 a| 
AutoSupport HTTPS 転送が無効です

AutoSupport メッセージのテクニカルサポートへの送信に使用される転送プロトコルを暗号化する必要があります。
 a| 
AutoSupport メッセージの転送プロトコルとして HTTPS を設定します
 a| 
クラスタ上の AutoSupport メッセージの転送プロトコルとして HTTPS を設定します。



 a| 
クラスタ負荷の不均衡しきい値を超過

クラスタ内のノード間で負荷が不均衡になっています。このイベントは、ノード間の使用済みパフォーマンス容量の差が 30% を超えた場合に生成されます。
 a| 
クラスタワークロードを分散します
 a| 
Unified Manager は別のノードに移動することで不均衡が最も解消されるボリュームを特定し、そのボリュームを移動します。



 a| 
クラスタ容量の不均衡しきい値を超過

クラスタ内のアグリゲート間で容量が不均衡になっています。このイベントは、アグリゲート間の使用済み容量の差が 70% を超えた場合に生成されます。
 a| 
クラスタ容量を分散します
 a| 
Unified Manager は別のアグリゲートに移動することで不均衡が最も解消されるボリュームを特定し、そのボリュームを移動します。



 a| 
使用済みパフォーマンス容量のしきい値を超過

1 つ以上のアクティブなワークロードによる利用率を下げないと、ノードの負荷が過剰になる可能性があります。このイベントは、ノードの使用済みパフォーマンス容量の値が 12 時間以上 100% を超えた場合に生成されます。
 a| 
ノードの高負荷を制限します
 a| 
Unified Manager は IOPS が高いボリュームを特定し、想定およびピークの過去の IOPS レベルを使用して QoS ポリシーを適用して、ノードの負荷を軽減します。



 a| 
動的イベントの警告しきい値を超過

一部のワークロードの負荷が異常に高いためにノードがすでに過負荷状態です。
 a| 
ノードの過負荷を軽減します
 a| 
Unified Manager は IOPS が高いボリュームを特定し、想定およびピークの過去の IOPS レベルを使用して QoS ポリシーを適用して、ノードの負荷を軽減します。



 a| 
テイクオーバーを実行できません

フェイルオーバーが無効になっているため、停止中またはリブート中のノードが使用可能な状態に戻るまではノードのリソースへのアクセスが失われます。
 a| 
ノードフェイルオーバーを有効にします
 a| 
Unified Manager が該当するコマンドを送信し、クラスタ内のすべてのノードのフェイルオーバーを有効にします。



 a| 
オプション cf.takeover.on_panic の設定が OFF になっています

ノードシェル・オプション「cf.takeover.on_panic」は、HA構成のシステムで問題 を原因 できる* off *に設定されています。
 a| 
パニック時のテイクオーバーを有効にする
 a| 
Unified Manager が該当するコマンドを送信し、この設定を * on * に変更します。



 a| 
ノードシェルオプション snapmirror.enable を無効化

古いノードシェル・オプション「snapmirror.enable」は* on *に設定されており、ONTAP 9.3以降へのアップグレード後、ブート時に問題 を原因 することができます。
 a| 
snapmirror.enable オプションを off に設定します
 a| 
Unified Manager が該当するコマンドを送信し、この設定を * off * に変更します。



 a| 
Telnet が有効です

Telnet は安全性が高くなく、暗号化されていない方法でデータが渡されるため、潜在的なセキュリティ問題を示します。
 a| 
Telnet を無効にします
 a| 
Unified Manager が適切なコマンドをクラスタに送信し、 Telnet を無効にします。

|===