---
permalink: online-help/reference-storage-vm-performance-information-page.html 
sidebar: sidebar 
keywords:  
summary: Storage VM /パフォーマンス情報ページを使用して、SVMの設定済み属性のリストを表示します。この情報は、パフォーマンス関連の疑問を解決するのに役立ちます。 
---
= Storage VM / Performance Informationページ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Storage VM /パフォーマンス情報ページを使用して、SVMの設定済み属性のリストを表示します。この情報は、パフォーマンス関連の疑問を解決するのに役立ちます。



== Storage VMの属性

* * IP アドレス *
+
このSVMに接続されているすべてのインターフェイスのIPv4アドレスまたはIPv6アドレス。

* * IPspace *
+
このSVMが配置されているIPspace。

* *ドメイン名*
+
このSVMに接続されているインターフェイスの完全修飾ドメイン名（FQDN）。

* *サービスタイプ*
+
SVMのタイプ。

+
指定できる値は、クラスタ全体の管理SVMには「Admin」、IPspaceにはクラスタレベルの通信には「System」、データ提供用SVMには「Data」、ノード管理SVMには「Node」です。

* *容量（空き/合計）*
+
SVMで使用可能な合計ストレージ容量、GB、および現在使用可能なストレージ容量。

* * クラスタ *
+
SVMが属するクラスタの名前。名前をクリックすると、クラスタ/パフォーマンスエクスプローラのページにクラスタの詳細を表示できます。

* * ボリューム *
+
SVM内のボリュームの数。数をクリックすると、パフォーマンス/ボリュームインベントリページにボリュームを表示できます。

* * ネットワーク・インターフェイス *
+
SVMが使用できるネットワークインターフェイスの数。

* * データ・ネットワーク・インターフェイス *
+
SVMが使用できるデータネットワークインターフェイスの数とタイプ。

* *使用できるボリュームタイプ*
+
SVMで作成できるボリュームのタイプ。

+
SVMには、1つ以上のFlexVol またはFlexGroup ボリュームを含めることができます。

* * 許可されたプロトコル *
+
このSVMで処理できるすべてのプロトコルのリスト。使用可能なプロトコルは、FC / FCoE、iSCSI、HTTP、NDMP、NVMeです。NFS、CIFSです。

* * ポートセット *
+
FCPまたはiSCSIプロトコル用に定義されている場合、このSVMに割り当てられているポートセット。


