---
permalink: online-help/task-exporting-storage-data-as-reports.html 
sidebar: sidebar 
keywords:  
summary: ストレージデータをさまざまな出力形式でエクスポートし、エクスポートしたデータを使用してレポートを作成できます。たとえば、未解決の重大イベントが 10 件ある場合、イベント管理のインベントリページからデータをエクスポートしてレポートを作成し、問題を解決できる管理者にレポートを送信できます。 
---
= ストレージデータをレポートとしてエクスポートする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージデータをさまざまな出力形式でエクスポートし、エクスポートしたデータを使用してレポートを作成できます。たとえば、未解決の重大イベントが 10 件ある場合、イベント管理のインベントリページからデータをエクスポートしてレポートを作成し、問題を解決できる管理者にレポートを送信できます。



== このタスクについて

にデータをエクスポートできます `.csv` ファイル、 `.xlsx` ファイル、または `.pdf` ストレージおよび*ネットワーク*インベントリページから文書化し、エクスポートしたデータを使用してレポートを作成します。製品には、他の場所のみがあります `.csv` または `.pdf` ファイルを生成できます。



== 手順

. 次のいずれかを実行します。


[cols="2*"]
|===
| エクスポートする項目 | 手順 


 a| 
ストレージオブジェクトのインベントリの詳細
 a| 
左側のナビゲーションメニューから * Storage * または * Network * をクリックし、ストレージオブジェクトを選択します。システムで提供されているビューのいずれか、または作成したカスタムビューを選択します。



 a| 
QoS ポリシーグループの詳細
 a| 
左側のナビゲーションメニューから、 * Storage * > * QoS Policy Groups * をクリックします。



 a| 
ストレージ容量と保護の履歴の詳細
 a| 
ストレージ * > * アグリゲート * または * ストレージ * > * ボリューム * をクリックして、 1 つまたは複数のアグリゲートまたはボリュームを選択します。



 a| 
イベントの詳細
 a| 
左側のナビゲーションメニューから、 * イベント管理 * をクリックします。



 a| 
上位 10 個のストレージオブジェクトのパフォーマンスの詳細
 a| 
[ * ストレージ * > * クラスタ * > * パフォーマンス：すべてのクラスタ * ] をクリックし、クラスタを選択して [ * パフォーマンストップ * ] タブを選択します。次に、ストレージオブジェクトとパフォーマンスカウンタを選択します。

|===
. [*Reports] ボタン（または一部の UI ページの [*Export*] ボタン）をクリックします。
. 「 * CSV のダウンロード * 」、「 PDF のダウンロード * 」、または「 * Excel のダウンロード * 」をクリックして、エクスポート要求を確認します。
+
Top Performers タブでは、表示している単一のクラスタまたはデータセンター内のすべてのクラスタの統計のレポートをダウンロードできます。

+
ファイルがダウンロードされます。

. 該当するアプリケーションでファイルを開きます。

