---
permalink: online-help/task-resuming-scheduled-transfers-on-a-quiesced-relationship.html 
sidebar: sidebar 
keywords:  
summary: 関係を休止してスケジュールされた転送の実行を停止したら、再開を使用してスケジュールされた転送を再度有効にし、ソースボリュームまたはプライマリボリュームのデータを保護します。スケジュールされた次回の転送時に、チェックポイントが存在する場合は、チェックポイントから転送が再開されます。 
---
= 休止中の関係のスケジュールされた転送をボリューム関係ページで再開しています
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
関係を休止してスケジュールされた転送の実行を停止したあと、 * Resume * を使用してスケジュールされた転送を再度有効にし、ソースボリュームまたはプライマリボリュームのデータを保護することができます。スケジュールされた次回の転送時に、チェックポイントが存在する場合は、チェックポイントから転送が再開されます。



== 作業を開始する前に

* アプリケーション管理者またはストレージ管理者のロールが必要です。
* Workflow Automation のセットアップが完了している必要があります。




== このタスクについて

転送を再開する休止中の関係を 10 個まで選択できます。



== 手順

. [*ボリューム関係*]ページで、関係が休止されている1つ以上のボリュームを選択し、ツールバーで[*再開]をクリックします。
. [* Resume * （続行） ] ダイアログボックスで、 [* Continue * （続行） ] をクリックします。
+
ボリューム関係のページに戻ります。

. 関連するジョブタスクを表示してその進捗状況を追跡するには、 * ボリューム関係 * ページの上部に表示されるジョブのリンクをクリックします。
. 次のいずれかを実行します。
+
** ジョブが 1 つだけ表示されている場合は、ジョブの詳細ページで「 * 更新 * 」をクリックして、保護設定ジョブに関連するタスクリストとタスクの詳細を更新し、ジョブが完了したかどうかを確認します。
** 複数のジョブが表示される場合は、
+
... [ ジョブ ] ページで、詳細を表示するジョブをクリックします。
... [ ジョブの詳細 ] ページで、 [*Refresh] をクリックして、保護設定ジョブに関連するタスクリストとタスクの詳細を更新し、ジョブが完了したかどうかを確認します。ジョブが完了すると、次回のスケジュールされた転送の実行時にデータ転送が再開されます。





