---
permalink: online-help/task-restoring-a-mysql-database-backup-on-windows.html 
sidebar: sidebar 
keywords: restore,windows 
summary: データ損失やデータ破損が発生した場合、リストア機能を使用して Unified Manager を以前の安定した状態にリストアすることで損失を最小限に抑えることができます。Unified Manager の MySQL データベースは、 Unified Manager メンテナンスコンソールを使用してローカルとリモートのどちらの Windows システムにもリストアできます。 
---
= Windows での MySQL データベースバックアップのリストア
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
データ損失やデータ破損が発生した場合、リストア機能を使用して Unified Manager を以前の安定した状態にリストアすることで損失を最小限に抑えることができます。Unified Manager の MySQL データベースは、 Unified Manager メンテナンスコンソールを使用してローカルとリモートのどちらの Windows システムにもリストアできます。



== 作業を開始する前に

* Windows の管理者権限が必要です。
* リストア処理を実行するシステムに Unified Manager のバックアップファイルとデータベースリポジトリディレクトリの内容をコピーしておく必要があります。
+
バックアップファイルはデフォルトのディレクトリにコピーすることを推奨します `\ProgramData\NetApp\OnCommandAppData\ocum\backup`。データベースリポジトリのファイルは、にコピーする必要があります `\database_dumps_repo` のサブディレクトリ `\backup` ディレクトリ。

* バックアップファイルはにする必要があります `.7z` を入力します。




== このタスクについて

リストア機能は、プラットフォームおよびバージョンに固有の機能です。Unified Manager の MySQL バックアップは、同じバージョンの Unified Manager にのみリストアできます。また、 Windows のバックアップは、 Windows プラットフォームにのみリストアできます。

[TIP]
====
フォルダ名にスペースが含まれている場合は、バックアップファイルの絶対パスまたは相対パスを二重引用符で囲む必要があります。

====


== 手順

. 新しいサーバへのリストアを実行する場合は、 Unified Manager のインストールの完了後に、 UI を起動したり、クラスタ、ユーザ、または認証設定を設定したりしないでください。この情報は、リストアプロセスでバックアップファイルに取り込まれます。
. 管理者のクレデンシャルで Unified Manager システムにログインします。
. Windows 管理者として PowerShell を起動します。
. 入力するコマンド `maintenance_console` を押します。
. メンテナンスコンソール * メインメニュー * で、 * バックアップリストア * オプションの番号を入力します。
. 「 MySQL バックアップのリストア」 * の番号を入力します。
. プロンプトが表示されたら、バックアップファイルの絶対パスを入力します。
+
[listing]
----
Bundle to restore from: \ProgramData\NetApp\OnCommandAppData\ocum\backup\UM_9.8.N151118.2300_backup_windows_02-20-2020-02-51.7z
----
+
リストア処理が完了したら、 Unified Manager にログインできます。





== 完了後

バックアップをリストアしたあとに OnCommand Workflow Automation サーバが動作しない場合は、次の手順を実行します。

. Workflow Automation サーバで、 Unified Manager サーバの IP アドレスを最新のマシンを参照するように変更します。
. 手順 1 で取得に失敗した場合は、 Unified Manager サーバでデータベースパスワードをリセットします。

