---
permalink: api-automation/concept-rest-services-offered-in-oncommand-api-services.html 
sidebar: sidebar 
keywords:  
summary: Active IQ Unified Manager API の使用を開始する前に、提供される REST サービスと処理について理解しておく必要があります。 
---
= Active IQ Unified Manager で提供される REST サービス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Manager API の使用を開始する前に、提供される REST サービスと処理について理解しておく必要があります。

API サーバの設定に使用されるプロビジョニング API と管理 API では、読み取り（ GET ）処理または書き込み（ POST 、 PATCH 、 DELETE ）処理がサポートされます。API でサポートされる GET 、 PATCH 、 POST 、および DELETE 処理のいくつかの例を次に示します。

* GETの例： `GET /datacenter/cluster/clusters` データセンター内のクラスタの詳細を取得します。によって返されるレコードの最大数 `GET` 動作は1000です。


[NOTE]
====
API を使用すると、レコードをサポートされている属性でフィルタ、ソート、および並べ替えることができます。

====
* POSTの例： `POST /datacenter/svm/svms` カスタムのStorage Virtual Machine（SVM）を作成します。
* PATCHの例： `+PATCH /datacenter/svm/svms/{key}+` 一意のキーを使用してSVMのプロパティを変更します。
* 削除の例： `+DELETE /storage-provider/access-endpoints/{key}+` 一意のキーを使用して、LUN、SVM、またはファイル共有からアクセスエンドポイントを削除します。


API を使用して実行できる REST 処理は、オペレータ、ストレージ管理者、またはアプリケーション管理者ユーザのロールによって異なります。

[cols="2*"]
|===
| ユーザロール | サポートされている REST メソッド 


 a| 
演算子
 a| 
データへの読み取り専用アクセス。このロールのユーザは、すべての GET 要求を実行できます。



 a| 
ストレージ管理者
 a| 
すべてのデータへの読み取りアクセス。このロールのユーザは、すべての GET 要求を実行できます。

また、管理、ストレージサービスオブジェクト、ストレージ管理オプションなどの特定のアクティビティを実行するための書き込みアクセス（ PATCH 、 POST 、および DELETE 要求を実行するため）が可能です。



 a| 
アプリケーション管理者
 a| 
すべてのデータへの読み取りおよび書き込みアクセス。このロールのユーザは、すべての機能に対する GET 、 PATCH 、 POST 、および DELETE 要求を実行できます。

|===
すべての REST 処理の詳細については、 _ オンラインの API ドキュメントを参照してください。
