---
permalink: api-automation/concept-job-api.html 
sidebar: sidebar 
keywords:  
summary: management-server カテゴリのジョブ API を使用すると、非同期処理の実行の詳細を表示できます。 
---
= ジョブの表示
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
を使用できます `jobs` のAPI `management-server` 非同期操作の実行の詳細を表示するカテゴリ。

Active IQ Unified Manager では、リソースの追加や変更などの処理は、同期および非同期の API 呼び出しによって実行されます。非同期で実行されるようにスケジュールされている呼び出しは、その呼び出しに対して作成されたジョブオブジェクトによって追跡できます。各ジョブオブジェクトには、識別用の一意のキーがあります。各ジョブオブジェクトはジョブオブジェクト URI を返し、ジョブの進捗状況を確認および追跡できます。この API を使用して、各実行の詳細を取得できます。

この API を使用して、履歴データを含む、データセンターのすべてのジョブオブジェクトを照会できます。デフォルトですべてのジョブを照会すると、 Web UI および API インターフェイスからトリガーされた最新 20 件のジョブの詳細が返されます。組み込みのフィルタを使用して、特定のジョブを表示します。ジョブキーを使用して特定のジョブの詳細を照会し、リソースに対して次の処理セットを実行することもできます。

[cols="4*"]
|===
| カテゴリ | HTTP 動詞 | パス | 説明 


 a| 
management-server
 a| 
取得
 a| 
`/management-server/jobs`
 a| 
すべてのジョブのジョブ詳細を返します。ソート順が指定されていない場合は、最後に送信されたジョブオブジェクトが先頭に返されます。



 a| 
management-server
 a| 
取得
 a| 
`+/management-server/jobs/{key}+`

ジョブオブジェクトのジョブキーを入力して、そのジョブの具体的な詳細を表示します。
 a| 
特定のジョブオブジェクトの詳細を返します。

|===