---
permalink: api-automation/concept-administration-apis.html 
sidebar: sidebar 
keywords:  
summary: 管理カテゴリの API を使用して、バックアップ設定を変更したり、バックアップファイル情報とクラスタ証明書を確認したり、 ONTAP クラスタを Active IQ Unified Manager データソースとして管理したりできます。 
---
= 管理タスクの実行
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
のAPIを使用できます `administration` バックアップ設定を変更するカテゴリで、バックアップファイル情報とクラスタ証明書を確認し、ONTAP クラスタをActive IQ Unified Manager データソースとして管理する。

[NOTE]
====
これらの処理を実行するには、アプリケーション管理者ロールが必要です。また、 Unified Manager Web UI を使用してこれらの設定を行うこともできます。

====
[cols="3*"]
|===
| HTTP 動詞 | パス | 説明 


 a| 
`GET`

`PATCH`
 a| 
`/admin/backup-settings`

`/admin/backup-settings`
 a| 
を使用できます `GET` デフォルトでUnified Managerで設定されているバックアップスケジュールの設定を表示する方法。次のことを確認できます。

* スケジュールが有効か無効か
* スケジュールされたバックアップの頻度（日単位または週単位）
* バックアップの時刻
* アプリケーションに保持するバックアップファイルの最大数


バックアップの時刻はサーバのタイムゾーンにあります。

データベースのバックアップ設定は、 Unified Manager ではデフォルトで有効になっており、バックアップスケジュールを作成することはできません。ただし、を使用することはできます `PATCH` メソッドを使用して、デフォルト設定を変更します。



 a| 
`GET`
 a| 
`/admin/backup-file-info`
 a| 
バックアップダンプファイルは、 Unified Manager のバックアップスケジュールが変更されるたびに生成されます。このメソッドを使用すると、変更したバックアップ設定に従ってバックアップファイルが生成されているかどうか、およびファイルの情報が変更した設定と一致するかどうかを確認できます。



 a| 
`GET`
 a| 
`/admin/datasource-certificate`
 a| 
このメソッドを使用して、信頼ストアからデータソース（クラスタ）証明書を表示できます。ONTAP クラスタを Unified Manager データソースとして追加する前に、証明書を検証する必要があります。



 a| 
`GET`

`POST`

`PATCH`

`DELETE`
 a| 
`/admin/datasources/clusters`

`+/admin/datasources/clusters/{key}+`
 a| 
を使用できます `GET` Unified Managerで管理されているデータソース（ONTAP クラスタ）の詳細を取得する方法。

新しいクラスタを Unified Manager にデータソースとして追加することもできます。クラスタを追加するには、ホスト名、ユーザ名、パスワードが必要です。

Unified Manager のデータソースとして管理されるクラスタを変更および削除するには、 ONTAP クラスタキーを使用します。

|===