---
permalink: api-automation/concept-data-center-apis.html 
sidebar: sidebar 
keywords:  
summary: データセンターカテゴリの REST API を使用して、クラスタ、ノード、アグリゲート、 Storage VM など、データセンター内のストレージオブジェクトを管理できます。 ボリューム、 LUN 、ファイル共有、ネームスペース。これらの API はオブジェクトの設定を照会でき、一部の API を使用してオブジェクトの追加、削除、または変更の処理を実行できます。 
---
= データセンター内のストレージオブジェクトの管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
のREST API `datacenter` カテゴリを使用すると、クラスタ、ノード、アグリゲート、Storage VMなど、データセンター内のストレージオブジェクトを管理できます。 ボリューム、LUN、ファイル共有、ネームスペース。これらの API はオブジェクトの設定を照会でき、一部の API を使用してオブジェクトの追加、削除、または変更の処理を実行できます。

これらの API のほとんどはクラスタをまたいだ集計値を提供する GET 呼び出しで、フィルタ、ソート、およびページ付けをサポートします。これらの API を実行すると、データベースからデータが返されます。したがって、新たに作成されたオブジェクトは、次の取得サイクルで検出されるまで応答に表示されません。

特定のオブジェクトの詳細を照会するには、そのオブジェクトの一意の ID を入力する必要があります。例：

[listing]
----
curl -X GET "https://<hostname>/api/datacenter/cluster/clusters/4c6bf721-2e3f-11e9-a3e2-00a0985badbb" -H "accept: application/json" -H "Authorization: Basic <Base64EncodedCredentials>"
----
[NOTE]
====
cURL コマンド、例、要求、および API への応答は、 Swagger API インターフェイスで参照できます。Swagger にも記載されているとおり、結果を特定のパラメータでフィルタおよび順序付けすることができます。これらの API を使用して、クラスタ、ボリューム、 Storage VM などの特定のストレージオブジェクトについての結果をフィルタリングできます。

====
[cols="3*"]
|===
| HTTP 動詞 | パス | 説明 


 a| 
`GET`
 a| 
`/datacenter/cluster/clusters`

`+/datacenter/cluster/clusters/{key}+`
 a| 
このメソッドを使用して、データセンター全体の ONTAP クラスタの詳細を表示できます。API は、クラスタの IPv4 アドレスや IPv6 アドレス、ノードの健全性、パフォーマンス容量、ハイアベイラビリティ（ HA ）ペアなどのノードに関する情報を返し、クラスタがオール SAN アレイかどうかを示します。



 a| 
`GET`
 a| 
`/datacenter/cluster/nodes`

`+/datacenter/cluster/nodes/{key}+`
 a| 
このメソッドを使用して、データセンター内のノードの詳細を表示できます。ノードのクラスタ、ノードの健全性、パフォーマンス容量、およびハイアベイラビリティ（ HA ）ペアに関する情報を表示できます。



 a| 
`GET`
 a| 
`/datacenter/protocols/cifs/shares`

`+/datacenter/protocols/cifs/shares/{key}+`
 a| 
このメソッドを使用して、データセンター内の CIFS 共有の詳細を表示できます。クラスタ、 SVM 、およびボリュームの詳細以外にも、アクセス制御リスト（ ACL ）に関する情報が返されます。



 a| 
`GET`
 a| 
`/datacenter/protocols/nfs/export-policies`

`+/datacenter/protocols/nfs/export-policies/{key}+`
 a| 
このメソッドを使用して、サポートされている NFS サービスのエクスポートポリシーの詳細を表示できます。

このメソッドを使用して、クラスタまたは Storage VM のエクスポートポリシーを照会し、 NFS ファイル共有のプロビジョニングに使用できます。ワークロードでのエクスポートポリシーの割り当てと再利用の詳細については、「 CIFS および NFS ファイル共有のプロビジョニング」を参照してください。



 a| 
`GET`
 a| 
`/datacenter/storage/aggregates`

`+/datacenter/storage/aggregates/{key}+`
 a| 
このメソッドを使用して、データセンター内のすべてのアグリゲートまたは特定のアグリゲートを表示し、ワークロードのプロビジョニングや監視を行うことができます。クラスタとノードの詳細、使用済みパフォーマンス容量、使用可能なスペースと使用済みのスペース、 Storage Efficiency などの情報が返されます。



 a| 
`GET`
 a| 
`/datacenter/storage/luns`

`+/datacenter/storage/luns/{key}+`
 a| 
このメソッドを使用して、データセンター全体のすべての LUN を表示できます。クラスタと SVM の詳細、 QoS ポリシー、 igroup など、 LUN に関する情報を表示できます。



 a| 
`GET`
 a| 
`/datacenter/storage/qos/policies`

`+/datacenter/storage/qos/policies/{key}+`
 a| 
このメソッドを使用して、データセンター内のストレージオブジェクトに適用可能なすべての QoS ポリシーの詳細を表示できます。クラスタと SVM の詳細、固定またはアダプティブのポリシーの詳細、そのポリシーに該当するオブジェクトの数などの情報が返されます。



 a| 
`GET`
 a| 
`/datacenter/storage/qtrees`

`+/datacenter/storage/qtrees/{key}+`
 a| 
このメソッドを使用して、すべての FlexVol または FlexGroup ボリュームについて、データセンター全体の qtree の詳細を表示できます。クラスタと SVM の詳細、 FlexVol ボリューム、エクスポートポリシーなどの情報が返されます。



 a| 
`GET`
 a| 
`/datacenter/storage/volumes`

`+/datacenter/storage/volumes/{key}+`
 a| 
このメソッドを使用して、データセンター内のすべてのボリュームを表示できます。SVMやクラスタの詳細、QoSポリシーやエクスポートポリシーなど、ボリュームのタイプがであるかどうかを示す情報 `read-write, data-protection, or load-sharing`が返されます。

FlexVol および FlexClone ボリュームについては、それぞれのアグリゲートに関する情報を表示できます。FlexGroup ボリュームの場合、コンスティチュエントアグリゲートのリストが表示されます。



 a| 
`GET`

`POST`

`DELETE`

`PATCH`
 a| 
`/datacenter/protocols/san/igroups`

`+/datacenter/protocols/san/igroups/{key}+`
 a| 
特定の LUN ターゲットへのアクセスを許可されたイニシエータグループ（ igroup ）を割り当てることができます。既存の igroup がある場合は、その igroup を割り当てることができます。igroup を作成して、 LUN に割り当てることもできます。

これらのメソッドを使用して、 igroup の照会、作成、削除、および変更を実行できます。

注意事項：

* `POST`：igroupの作成中に、アクセスを割り当てるStorage VMを指定できます。
* `DELETE`：特定のigroupを削除するには、入力パラメータとしてigroupキーを指定する必要があります。すでに LUN に割り当てられている igroup は削除できません。
* `PATCH`：特定のigroupを変更するには、入力パラメータとしてigroupキーを指定する必要があります。また、更新するプロパティとその値を入力する必要があります。




 a| 
`GET`

`POST`

`DELETE`

`PATCH`
 a| 
`/datacenter/svm/svms`

`+/datacenter/svm/svms/{key}+`
 a| 
これらのメソッドを使用して、 Storage Virtual Machine （ Storage VM ）を表示、作成、削除、および変更できます。

注意事項：

* `POST`：作成するStorage VMオブジェクトを入力パラメータとして指定する必要があります。カスタムの Storage VM を作成して、必要なプロパティを割り当てることができます。
+
[NOTE]
====
環境で SLO ベースのワークロードプロビジョニングを有効にしている場合、 Storage VM を作成する際には、 CIFS または SMB 、 NFS 、 FCP など、 LUN とファイル共有のプロビジョニングに必要なすべてのプロトコルがこの環境でサポートされていることを確認してください。 および iSCSI などです。Storage VM が必要なサービスをサポートしていないと、プロビジョニングワークフローが失敗することがあります。対応するワークロードタイプのサービスも有効にすることを推奨します。

====
* `DELETE`：特定のStorage VMを削除するには、Storage VMキーを指定する必要があります。
+
[NOTE]
====
環境で SLO ベースのワークロードプロビジョニングを有効にしている場合、ストレージワークロードがプロビジョニングされている Storage VM は削除できません。CIFS または SMB サーバが設定されている Storage VM を削除すると、ローカルの Active Directory 設定に加えて CIFS サーバまたは SMB サーバも削除されます。ただし、 CIFS サーバまたは SMB サーバの名前は Active Directory 設定に残っているため、 Active Directory サーバから手動で削除する必要があります。

====
* `PATCH`：特定のStorage VMを変更するには、Storage VMキーを指定する必要があります。また、更新するプロパティとその値を入力する必要があります。


|===