---
permalink: api-automation/concept-security-apis.html 
sidebar: sidebar 
keywords:  
summary: セキュリティカテゴリの API を使用して、 Active IQ Unified Manager 内の選択したクラスタオブジェクトへのユーザアクセスを制御できます。ローカルユーザまたはデータベースユーザを追加できます。また、認証サーバに属するリモートユーザやリモートグループを追加することもできます。ユーザに割り当てたロールの権限に基づいて、ストレージオブジェクトを管理したり、 Unified Manager でデータを表示したりできます。 
---
= ユーザの管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
のAPIを使用できます `security` Active IQ Unified Manager で選択したクラスタオブジェクトへのユーザアクセスを制御するカテゴリ。ローカルユーザまたはデータベースユーザを追加できます。また、認証サーバに属するリモートユーザやリモートグループを追加することもできます。ユーザに割り当てたロールの権限に基づいて、ストレージオブジェクトを管理したり、 Unified Manager でデータを表示したりできます。

[NOTE]
====
これらの処理を実行するには、アプリケーション管理者ロールが必要です。また、 Unified Manager Web UI を使用してこれらの設定を行うこともできます。

====
のAPI `security` カテゴリ：を使用します `users` パラメータ。はユーザ名であり、は含まれません `key` ユーザエンティティの一意の識別子としてパラメータを指定します。

[cols="3*"]
|===
| HTTP 動詞 | パス | 説明 


 a| 
`GET`

`POST`
 a| 
`/security/users`

`/security/users`
 a| 
これらのメソッドを使用して、ユーザの詳細を取得したり、 Unified Manager に新しいユーザを追加したりできます。

ユーザのタイプに基づいて、ユーザに特定のロールを追加できます。ユーザを追加する際には、ローカルユーザ、メンテナンスユーザ、およびデータベースユーザのパスワードを指定する必要があります。



 a| 
`GET`

`PATCH`

`DELETE`
 a| 
`+/security/users/{name}+`
 a| 
。 `GET` メソッドを使用すると、名前、Eメールアドレス、ロール、認証タイプなど、ユーザのすべての詳細を取得できます。。 `PATCH` メソッドを使用すると、詳細を更新できます。。 `DELETE` メソッドを使用すると、ユーザを削除できます。

|===