---
permalink: api-automation/concept-metrics-apis.html 
sidebar: sidebar 
keywords:  
summary: Active IQ Unified Manager には、データセンターカテゴリ下の一連の API が用意されており、データセンター内のクラスタおよびストレージオブジェクトのパフォーマンスデータを表示できます。これらの API は、クラスタ、ノード、 LUN 、ボリュームなどのさまざまなストレージオブジェクトのパフォーマンスデータを取得します。 アグリゲート、 Storage VM 
---
= パフォーマンス指標の表示
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Manager には、の一連のAPIが用意されています `/datacenter` データセンター内のクラスタおよびストレージオブジェクトのパフォーマンスデータを表示できるカテゴリ。これらの API は、クラスタ、ノード、 LUN 、ボリュームなどのさまざまなストレージオブジェクトのパフォーマンスデータを取得します。 アグリゲート、 Storage VM

。 `/metrics` および `/analytics` APIを使用すると、パフォーマンス指標をさまざまなビューで確認できます。データセンター内の次のストレージオブジェクトについて、さまざまなレベルの詳細にドリルダウンできます。

* クラスタ
* ノード
* Storage VMs
* アグリゲート
* 個のボリューム
* LUN


次の表は、間の比較を示しています `/metrics` および `/analytics` 取得したパフォーマンスデータの詳細を示すAPI。

[cols="2*"]
|===
| 指標 | 分析 


 a| 
1 つのオブジェクトのパフォーマンスの詳細。たとえば、などです `+/datacenter/cluster/clusters/{key}/metrics+` APIでを使用するには、クラスタキーをとして入力する必要があります `path` 特定のクラスタの指標を取得するためのパラメータ。
 a| 
データセンター内の同じタイプの複数のオブジェクトのパフォーマンスの詳細。たとえば、などです `/datacenter/cluster/clusters/analytics` APIは、データセンター内のすべてのクラスタの集合的な指標を取得します。



 a| 
読み出しの時間間隔パラメータに基づくストレージオブジェクトのパフォーマンス指標サンプル。
 a| 
特定の期間（72時間を超える）における特定のタイプのストレージオブジェクトのパフォーマンスの総合的な価値。



 a| 
ノードやクラスタの詳細など、オブジェクトの基本的な詳細が読み出されます。
 a| 
具体的な詳細は取得されません。



 a| 
一定期間の最小、最大、平均のパフォーマンス値などの累積カウンタが、読み取り、書き込み、合計などの単一のオブジェクトについて読み出されます。その他のカウンタ。たとえば、などです `+/datacenter/cluster/nodes/{key}/metrics+` APIがノードについて次の詳細を取得する（特にその他）。

[listing]
----
 {
      "iops": {
        "local": {
          "others": 100.53,
          "read": 100.53,
          "total": 100.53,
          "write": 100.53
        },
        "others": 100.53,
        "read": 100.53,
        "total": 100.53,
        "write": 100.53
      },
      "latency": {
        "others": 100.53,
        "read": 100.53,
        "total": 100.53,
        "write": 100.53
      },
      "performance_capacity": {
        "available_iops_percent": 0,
        "free_percent": 0,
        "system_workload_percent": 0,
        "used_percent": 0,
        "user_workload_percent": 0
      },
      "throughput": {
        "other": 100.53,
        "read": 100.53,
        "total": 100.53,
        "write": 100.53
      },
---- a| 
同じタイプのすべてのオブジェクトについて、集約された単一の値が表示されます。たとえば、などです `/datacenter/cluster/nodes/analytics` APIがすべてのノードに対して次の値を（特に）取得する。

[listing]
----
 {
      "iops": 2757.5723,
      "latency": 0.8266,
      "throughput": 13254.6992,
      "utilization_percent": 58.6488,
      "period": 72,
      "performance_capacity": {
        "used_percent": 63.5317,
        "available_iops_percent": 60731.3086
      },
----


 a| 
時間範囲とサンプルデータは、次のスケジュールに基づいています。データの時間範囲。例として、 1h 、 12h 、 1d 、 2d 、 3d があります。 15D 、 1w 、 1m 、 2m 、 3m 、 6M 。範囲が 3 日（ 72 時間）を超える場合は 1 時間のサンプルを取得し、それ以外の場合は 5 分のサンプルを取得します。各期間は次のとおりです。

* 1H ：直近 1 時間の測定値が 5 分以上にわたってサンプリングされます。
* 12 時間： 5 分以上にわたってサンプリングされた最新の 12 時間のメトリック。
* 1D ：直近の 1 日の測定値が 5 分以上にわたってサンプリングされます。
* 2D ：直近 2 日間の測定値が 5 分を超えてサンプリングされます。
* 3D ：直近 3 日間の測定値が 5 分を超えてサンプリングされます。
* 15D ： 1 時間にわたってサンプリングされた最新の 15 日間のメトリック。
* 1W ： 1 時間以上サンプリングされた最新の週のメトリック。
* 1M ：最近 1 時間でサンプリングされた月のメトリックス。
* 2M ：直近 2 カ月間の測定値が 1 時間以上にわたってサンプリングされます。
* 3M ：最近 3 カ月間の測定値が 1 時間以上サンプリングされています。
* 6M ：直近 6 カ月間の測定値が 1 時間以上にわたってサンプリングされます。


使用可能な値は、 1h 、 12h 、 1d 、 2d 、 3d です。 15D 、 1w 、 1m 、 2m 、 3m 、 6M

デフォルト値： 1h
 a| 
72時間を超えると、3日間です。このサンプルを計算する期間は、 ISO-8601 標準形式で表されます。

|===
次の表で、について説明します `/metrics` および `/analytics` APIの詳細をご覧ください。

[NOTE]
====
これらのAPIから返されるIOPSとパフォーマンスの指標には、たとえば2倍の値があります `100.53`。これらの浮動小数点値をパイプ（ | ）およびワイルドカード（ * ）文字でフィルタリングすることはできません。

====
[cols="3*"]
|===
| HTTP 動詞 | パス | 説明 


 a| 
`GET`
 a| 
`+/datacenter/cluster/clusters/{key}/metrics+`
 a| 
クラスタキーの入力パラメータで指定したクラスタのパフォーマンスデータ（サンプルと概要）を取得します。クラスタキーとUUID、時間範囲、IOPS、スループット、サンプル数などの情報が返されます。



 a| 
`GET`
 a| 
`/datacenter/cluster/clusters/analytics`
 a| 
は、データセンター内のすべてのクラスタのパフォーマンス指標の概要を取得します。必要な条件に基づいて結果をフィルタできます。集計 IOPS 、スループット、収集期間（時間数）などの値が返されます。



 a| 
`GET`
 a| 
`+/datacenter/cluster/nodes/{key}/metrics+`
 a| 
ノードキーの入力パラメータで指定したノードのパフォーマンスデータ（サンプルとサマリ）を取得します。ノード UUID 、時間範囲、 IOPS 、スループット、レイテンシ、パフォーマンスの概要、収集されたサンプル数、利用率などの情報が返されます。



 a| 
`GET`
 a| 
`/datacenter/cluster/nodes/analytics`
 a| 
は、データセンター内のすべてのノードのパフォーマンス指標の概要を取得します。必要な条件に基づいて結果をフィルタできます。ノードキーやクラスタキーなどの情報、および集計 IOPS 、スループット、収集期間（時間数）などの値が返されます。



 a| 
`GET`
 a| 
`+/datacenter/storage/aggregates/{key}/metrics+`
 a| 
aggregate キーの入力パラメータで指定したアグリゲートのパフォーマンスデータ（サンプルとサマリ）を取得します。時間範囲、 IOPS 、レイテンシ、スループット、パフォーマンス容量の概要、各カウンタで収集されたサンプル数、使用率などの情報が返されます。



 a| 
`GET`
 a| 
`/datacenter/storage/aggregates/analytics`
 a| 
データセンター内のすべてのアグリゲートのパフォーマンス指標の概要が取得されます。必要な条件に基づいて結果をフィルタできます。アグリゲートキーやクラスタキーなどの情報、および集計 IOPS 、スループット、収集期間（時間数）などの値が返されます。



 a| 
`GET`
 a| 
`+/datacenter/storage/luns/{key}/metrics+`

`+/datacenter/storage/volumes/{key}/metrics+`
 a| 
LUN またはボリュームキーの入力パラメータで指定された LUN またはファイル共有（ボリューム）のパフォーマンスデータ（サンプルとサマリ）を取得します。読み取り、書き込み、合計 IOPS 、レイテンシ、スループットの最小値、最大値、平均値の概要などの情報。 各カウンタについて収集されたサンプル数が返されます。



 a| 
`GET`
 a| 
`/datacenter/storage/luns/analytics`

`/datacenter/storage/volumes/analytics`
 a| 
データセンター内のすべての LUN またはボリュームのパフォーマンス指標の概要を取得します。必要な条件に基づいて結果をフィルタできます。Storage VM やクラスタキーなどの情報、および集計 IOPS 、スループット、収集期間（時間数）などの値が返されます。



 a| 
`GET`
 a| 
`+/datacenter/svm/svms/{key}/metrics+`
 a| 
Storage VM キーの入力パラメータで指定した Storage VM のパフォーマンスデータ（サンプルと概要）を取得します。など、サポートされている各プロトコルに基づくIOPSの概要 `nvmf, fcp, iscsi`および `nfs`、スループット、レイテンシ、収集されたサンプル数が返されます。



 a| 
`GET`
 a| 
`/datacenter/svm/svms/analytics`
 a| 
は、データセンター内のすべての Storage VM のパフォーマンス指標の概要を取得します。必要な条件に基づいて結果をフィルタできます。Storage VM の UUID 、アグリゲート IOPS 、レイテンシ、スループット、収集期間（時間数）などの情報が返されます。



 a| 
`GET`
 a| 
`/datacenter/cluster/licensing/licenses` `+/datacenter/cluster/licensing/licenses/{key}+`
 a| 
データセンター内のクラスタにインストールされているライセンスの詳細を返します。必要な条件に基づいて結果をフィルタできます。ライセンスキー、クラスタキー、有効期限、ライセンス範囲などの情報が返されます。ライセンスキーを入力すると、特定のライセンスの詳細を取得できます。

|===