---
permalink: api-automation/concept-managing-lun.html 
sidebar: sidebar 
keywords:  
summary: /storage-provider/LUNs API を使用して、データセンター環境の LUN を表示、追加、変更、および削除できます。 
---
= LUN の管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
を使用できます `/storage-provider/luns` データセンター環境内のLUNを表示、追加、変更、削除するためのAPI。

LUN をプロビジョニングする前に、 SVM が作成され、サポートされるプロトコルでプロビジョニングされていることを確認してください。プロビジョニング中にパフォーマンスサービスレベル（ PSL ）またはストレージ効率化ポリシー（ SEP ）を割り当てる場合は、 LUN を作成する前に PSL または SEP を作成する必要があります。



== LUN を表示します

Unified Manager 環境の LUN を表示するには、次のメソッドを使用します。Active IQ Unified Manager のデータソースとして ONTAP クラスタを追加すると、それらのクラスタのストレージワークロードが Unified Manager インスタンスに自動的に追加されます。この API は、 Unified Manager インスタンスに自動および手動で追加されたすべての LUN を取得します。特定の LUN の詳細を表示するには、 LUN キーを指定してこの API を実行します。

[cols="3*"]
|===
| カテゴリ | HTTP 動詞 | パス 


 a| 
ストレージプロバイダ
 a| 
取得
 a| 
`/storage-provider/luns`

`+/storage-provider/luns/{key}+`

|===


== LUN を追加します

SVM に LUN を追加するには、次のメソッドを使用します。

[cols="3*"]
|===
| カテゴリ | HTTP 動詞 | パス 


 a| 
ストレージプロバイダ
 a| 
投稿（ Post ）
 a| 
`/storage-provider/luns`

|===
[NOTE]
====
cURL要求で、オプションのパラメータの値を指定する場合 `volume_name_tag` 入力では、この値に基づいてLUNの作成時にボリューム名が付けられます。このタグにより、ボリュームを簡単に検索できます。要求にボリュームキーを指定した場合、このタギングはスキップされます。

====


== LUN を削除します

特定の LUN を削除するには、次のメソッドを使用します。特定の LUN を削除するには、 LUN キーを指定する必要があります。

[NOTE]
====
ONTAP でボリュームを作成し、そのボリュームで Unified Manager を使用して LUN をプロビジョニングした場合、この API を使用してすべての LUN を削除すると、ボリュームも ONTAP クラスタから削除されます。

====
[cols="3*"]
|===
| カテゴリ | HTTP 動詞 | パス 


 a| 
ストレージプロバイダ
 a| 
削除
 a| 
`+/storage-provider/luns/{key}+`

|===


== LUNs を変更する

LUN を変更してそのプロパティを更新するには、次のメソッドを使用します。特定の LUN を変更するには、 LUN キーを指定する必要があります。また、更新する LUN プロパティとその値を入力する必要があります。この API を使用して LUN アレイを更新する場合は ' API の使用に関する推奨事項を確認する必要があります

[NOTE]
====
この API の 1 回の呼び出しで更新できるプロパティは 1 つだけです。更新が複数ある場合は、この API を何度でも実行する必要があります。

====
[cols="3*"]
|===
| カテゴリ | HTTP 動詞 | パス 


 a| 
ストレージプロバイダ
 a| 
パッチ
 a| 
`+/storage-provider/luns/{key}+`

|===