---
permalink: install-vapp/task-deploying-unified-manager-vapp.html 
sidebar: sidebar 
keywords:  
summary: Unified Manager を導入するには、ソフトウェアをダウンロードし、仮想アプライアンスを導入し、メンテナンスユーザを作成してユーザ名とパスワードを設定し、 Web UI で初期セットアップを行います。 
---
= Unified Manager を導入します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager を導入するには、ソフトウェアをダウンロードし、仮想アプライアンスを導入し、メンテナンスユーザを作成してユーザ名とパスワードを設定し、 Web UI で初期セットアップを行います。



== 作業を開始する前に

* 導入に必要なシステム要件を確認し、満たしておく必要があります。
+
xref:concept-requirements-for-installing-unified-manager.adoc[システム要件]

* 次の情報があることを確認します。
+
** NetApp Support Siteのログインクレデンシャル
** VMware vCenter Server および vSphere Web Client にアクセスするためのクレデンシャル
** Unified Manager 仮想アプライアンスを導入する ESXi サーバの IP アドレス
** データストアのストレージスペースやメモリ要件など、データセンターに関する詳細情報
** IPv6 アドレスを使用する場合は、ホストで IPv6 が有効になっている必要があります。






== このタスクについて

Unified Manager は、 VMware ESXi サーバに仮想アプライアンスとして導入できます。

メンテナンスコンソールには、 SSH ではなく、 VMware コンソールを使用してアクセスする必要があります。

[NOTE]
====
Unified Manager 9.8以降では、VMware ToolsがOpen VM Toolsに置き換えられています  `open-vm-tools`）。VMware Toolsをインストールの一部としてインストールする必要がなくなりました。理由はです `open-vm-tools` は、Unified Managerインストールパッケージに含まれています。

====


== 完了後

導入と初期セットアップが完了したら、クラスタを追加するかメンテナンスコンソールで追加のネットワーク設定を行ってから、 Web UI にアクセスできます。
