---
permalink: install-linux/task-upgrading-the-host-os-from-rhel-6-x-to-7-x.html 
sidebar: sidebar 
keywords:  
summary: Unified Manager がインストールされている Red Hat Enterprise Linux 7.x システムを Red Hat Enterprise Linux 8.x にアップグレードする必要がある場合は、このトピックに記載されているいずれかの手順に従う必要があります。いずれの場合も、 Red Hat Enterprise Linux 7.x システムに Unified Manager のバックアップを作成し、そのバックアップを Red Hat Enterprise Linux 8.x システムにリストアする必要があります。 
---
= Red Hat Enterprise Linux 7.x から 8.x へのホスト OS のアップグレード
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager がインストールされている Red Hat Enterprise Linux 7.x システムを Red Hat Enterprise Linux 8.x にアップグレードする必要がある場合は、このトピックに記載されているいずれかの手順に従う必要があります。いずれの場合も、 Red Hat Enterprise Linux 7.x システムに Unified Manager のバックアップを作成し、そのバックアップを Red Hat Enterprise Linux 8.x システムにリストアする必要があります。



== このタスクについて

ここに記載する 2 つの方法の違いは、 Unified Manager のリストア処理を新しい 8.x サーバで実行する場合と同じサーバで実行する場合です。

この作業では、 Red Hat Enterprise Linux 7.x システムで Unified Manager のバックアップを作成する必要があるため、 Unified Manager がオフラインになる時間が最小限になるように、アップグレードプロセス全体を実行する準備ができてからバックアップを作成します。Red Hat Enterprise Linux 7.x システムをシャットダウンしたあと、新しい Red Hat Enterprise Linux 8.x を起動するまではデータが収集されないため、その間のデータは Unified Manager UI に表示されません。

バックアップとリストアのプロセスの詳細な手順については、 Active IQ Unified Manager オンラインヘルプを参照してください。

* 新しいサーバを使用したホスト OS のアップグレード *

Red Hat Enterprise Linux 8.x ソフトウェアをインストールできるスペアシステムがある場合は、 Red Hat Enterprise Linux 7.x システムが稼働している間にスペアシステムで Unified Manager のリストアを実行できるように、次の手順に従います。

. 新しいサーバに Red Hat Enterprise Linux 8.x ソフトウェアをインストールして設定します。
+
xref:reference-red-hat-and-centos-software-and-installation-requirements.adoc[Red Hat のソフトウェアとインストールの要件]

. Red Hat Enterprise Linux 8.x システムには、既存の Red Hat Enterprise Linux 7.x システムと同じバージョンの Unified Manager ソフトウェアをインストールします。
+
xref:concept-installing-unified-manager-on-rhel-or-centos.adoc[Red Hat Enterprise Linux への Unified Manager のインストール]

+
インストールが完了しても、 UI を起動したり、クラスタ、ユーザ、または認証設定を設定したりしないでください。この情報は、リストアプロセスでバックアップファイルに取り込まれます。

. Red Hat Enterprise Linux 7.xシステムのWeb UIの管理メニューで、Unified Managerのバックアップを作成し、バックアップファイルをコピーします (`.7z` ファイル）とデータベースリポジトリディレクトリの内容 (`/database-dumps-repo` サブディレクトリ）を外部の場所に追加します。
. Red Hat Enterprise Linux 7.x システムで、 Unified Manager をシャットダウンします。
. Red Hat Enterprise Linux 8.xシステムで、バックアップファイルをコピーします (`.7z` ファイル）を外部の場所からにコピーします `/opt/netapp/data/ocum-backup/` およびにデータベースリポジトリファイルを追加します `/database-dumps-repo` のサブディレクトリ `/ocum-backup` ディレクトリ。
. 次のコマンドを入力して、バックアップファイルから Unified Manager データベースをリストアします。 `um backup restore -f /opt/netapp/data/ocum-backup/<backup_file_name>`
. Web ブラウザに IP アドレスまたは URL を入力して Unified Manager Web UI を起動し、システムにログインします。


システムが正常に動作していることを確認したら、 Red Hat Enterprise Linux 7.x システムから Unified Manager を削除できます。

* 同じサーバ上のホスト OS のアップグレード *

Red Hat Enterprise Linux 8.x ソフトウェアをインストールできるスペアシステムがない場合は、次の手順に従います。

. Web UIの管理メニューで、Unified Managerのバックアップを作成し、バックアップファイルをコピーします (`.7z` ファイル）とデータベースリポジトリディレクトリの内容 (`/database-dumps-repo` サブディレクトリ）を外部の場所に追加します。
. システムから Red Hat Enterprise Linux 7.x イメージを削除し、システムを完全に消去します。
. 同じシステムに Red Hat Enterprise Linux 8.x ソフトウェアをインストールして設定します。
+
xref:reference-red-hat-and-centos-software-and-installation-requirements.adoc[Red Hat のソフトウェアとインストールの要件]

. Red Hat Enterprise Linux 8.x システムには、以前の Red Hat Enterprise Linux 7.x システムと同じバージョンの Unified Manager ソフトウェアをインストールします。
+
xref:concept-installing-unified-manager-on-rhel-or-centos.adoc[Red Hat Enterprise Linux への Unified Manager のインストール]

+
インストールが完了しても、 UI を起動したり、クラスタ、ユーザ、または認証設定を設定したりしないでください。この情報は、リストアプロセスでバックアップファイルに取り込まれます。

. バックアップファイルをコピーします (`.7z` ファイル）を外部の場所からにコピーします `/opt/netapp/data/ocum-backup/` およびにデータベースリポジトリファイルを追加します `/database-dumps-repo` のサブディレクトリ `/ocum-backup` ディレクトリ。
. 次のコマンドを入力して、バックアップファイルから Unified Manager データベースをリストアします。``um backup restore -f /opt/netapp/data/ocum-backup/<backup_file_name>``
. Web ブラウザに IP アドレスまたは URL を入力して Unified Manager Web UI を起動し、システムにログインします。

