---
permalink: install-linux/task-downloading-unified-manager.html 
sidebar: sidebar 
keywords:  
summary: Unified Managerをインストールするには、Unified Manager.zipファイルをNetApp Support Site からダウンロードする必要があります。 
---
= Unified Manager をダウンロードしています
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Managerをダウンロードする必要があります``.zip`` ファイルをNetApp Support Site から選択して、Unified Managerをインストールします。



== 作業を開始する前に

NetApp Support Siteのログインクレデンシャルが必要です。



== このタスクについて

ダウンロードする Unified Manager のインストールパッケージは、 Red Hat Enterprise Linux と CentOS の両方のシステムで共通です。



== 手順

. NetApp Support Site にログインし、Unified Managerの*ダウンロードページに移動します。 https://["NetApp Support Site"]
. 必要なバージョンの Unified Manager を選択し、エンドユーザライセンス契約（ EULA ）に同意します。
. Linux用のUnified Managerインストーラファイルをダウンロードし、を保存します `.zip` ファイルをターゲットシステム上のディレクトリにコピーします。
+
[NOTE]
====
使用している Red Hat Enterprise Linux システムに対応した正しいバージョンのインストーラファイルをダウンロードしていることを確認してください。Red Hat Enterprise Linux 7または8がインストールされているかどうかに基づいて、適切なバージョンのUnified Managerをダウンロードします``.zip`` ファイル。

====
. チェックサムを確認して、ソフトウェアが正しくダウンロードされたことを確認します。

